services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: menushield
      MYSQL_USER: menushield_user
      MYSQL_PASSWORD: menushield_password
    ports:
      - "3307:3306" # Vaihdettu portti 3307
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --init-file=/dev/null
    networks:
      - menushield-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      NODE_ENV: production
      DATABASE_URL: mysql://menushield_user:menushield_password@mysql:3306/menushield
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      PORT: 4000
    ports:
      - "4000:4000"
    depends_on:
      - mysql
    networks:
      - menushield-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - menushield-network

volumes:
  mysql_data:

networks:
  menushield-network:
    driver: bridge
