[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"
buildCommand = "cd backend"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
